services:
  wes-rabbitmq:
    image: rabbitmq:3.8.11-alpine
    ports:
      - "127.0.0.1:5672:5672"
    volumes:
      - "./configs/rabbitmq:/etc/rabbitmq:ro"
  wes-app-meta-cache:
    image: redis:7.0.4
    ports:
      - "127.0.0.1:6379:6379"
