apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
    - name: http
      port: 15672
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.11-management
          ports:
            - name: amqp
              containerPort: 5672
            - name: http
              containerPort: 15672
          volumeMounts:
            - name: config
              mountPath: /etc/rabbitmq
              readOnly: true
          resources:
            requests:
              cpu: "1"
              memory: "128Mi"
            limits:
              cpu: "2"
              memory: "512Mi"
      volumes:
        - name: config
          configMap:
            name: rabbitmq
