name: Run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: pip3 install https://github.com/waggle-sensor/pywaggle/archive/refs/tags/0.43.2.zip
      - name: Run tests
        run: python3 test.py
