name: Run tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start service containers
        run: make svc-up
      - name: Wait until containers are ready
        run: sleep 10 && timeout 60 docker-compose exec -T -- wes-rabbitmq rabbitmqctl await_startup && sleep 10
      - name: Run tests
        run: make test
